version: "2"
services:
  node-grpc-boilerplate:
    container_name: node-grpc
    build: .
    ports:
     - "50051:50051"
    volumes:
      - "./config:/usr/src/app/config"
      - "./src:/usr/src/app/src"
      - "./proto:/proto"
    expose:
     - "50051"